package basedatos;
// Generated 13:40:24, 01/12/2020 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer idBook;
	private String code;
	private String title;
	private String authors;
	private Integer year;
	private Set loans = new HashSet(0);

	public Book() {
	}

	public Book(String code, String title, String authors, Integer year, Set loans) {
		this.code = code;
		this.title = title;
		this.authors = authors;
		this.year = year;
		this.loans = loans;
	}

	public Integer getIdBook() {
		return this.idBook;
	}

	public void setIdBook(Integer idBook) {
		this.idBook = idBook;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Set getLoans() {
		return this.loans;
	}

	public void setLoans(Set loans) {
		this.loans = loans;
	}

	@Override
	public String toString() {
		return "Book [idBook=" + idBook + ", code=" + code + ", title=" + title + ", authors=" + authors + ", year="
				+ year+ "]";
	}
	

}
