package basedatos;
// Generated 13:40:24, 01/12/2020 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer idClient;
	private String dni;
	private String name;
	private String email;
	private Set loans = new HashSet(0);

	public Client() {
	}

	public Client(String dni, String name, String email, Set loans) {
		this.dni = dni;
		this.name = name;
		this.email = email;
		this.loans = loans;
	}

	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getLoans() {
		return this.loans;
	}

	public void setLoans(Set loans) {
		this.loans = loans;
	}

	@Override
	public String toString() {
		return "Client [idClient=" + idClient + ", dni=" + dni + ", name=" + name + ", email=" + email +  "]";
	}
	

}
