package dto;
// Generated 11 ene. 2021 13:26:11 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer idCliente;
	private String nome;
	private String enderezo;
	private Set telefonoses = new HashSet(0);
	private Set facturases = new HashSet(0);

	public Clientes() {
	}

	public Clientes(String nome, String enderezo, Set telefonoses, Set facturases) {
		this.nome = nome;
		this.enderezo = enderezo;
		this.telefonoses = telefonoses;
		this.facturases = facturases;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEnderezo() {
		return this.enderezo;
	}

	public void setEnderezo(String enderezo) {
		this.enderezo = enderezo;
	}

	public Set getTelefonoses() {
		return this.telefonoses;
	}

	public void setTelefonoses(Set telefonoses) {
		this.telefonoses = telefonoses;
	}

	public Set getFacturases() {
		return this.facturases;
	}

	public void setFacturases(Set facturases) {
		this.facturases = facturases;
	}

	@Override
	public String toString() {
		return "ID[" + idCliente + "], nome=" + nome + ", enderezo=" + enderezo + ", teléfonos"
				+ telefonoses;
	}

}
