package dto;
// Generated 11 ene. 2021 13:26:11 by Hibernate Tools 5.2.12.Final

/**
 * Facturas generated by hbm2java
 */
public class Facturas implements java.io.Serializable {

	private Integer idFactura;
	private Clientes clientes;
	private String detalle;
	private Double importe;

	public Facturas() {
	}

	public Facturas(Clientes clientes, String detalle, Double importe) {
		this.clientes = clientes;
		this.detalle = detalle;
		this.importe = importe;
	}

	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	@Override
	public String toString() {
		return "Factura [" + idFactura + "]\nCLIENTE = " + clientes + "\nDETALLE = " + detalle + "\nIMPORTE = "
				+ importe+"\n";
	}

}
