package dto;
// Generated 10 ene. 2021 17:37:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente2 generated by hbm2java
 */
public class Cliente2 implements java.io.Serializable {

	private Integer idCliente;
	private String dni;
	private String nome;
	private Set pedido2s = new HashSet(0);

	public Cliente2() {
	}

	public Cliente2(String dni, String nome, Set pedido2s) {
		this.dni = dni;
		this.nome = nome;
		this.pedido2s = pedido2s;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getPedido2s() {
		return this.pedido2s;
	}

	public void setPedido2s(Set pedido2s) {
		this.pedido2s = pedido2s;
	}

	@Override
	public String toString() {
		return "Cliente [idCliente=" + idCliente + ", dni=" + dni + ", nome=" + nome + "]";
	}

}
