package dto;
// Generated 10 ene. 2021 17:37:45 by Hibernate Tools 5.2.12.Final

/**
 * LineaPedido2 generated by hbm2java
 */
public class LineaPedido2 implements java.io.Serializable {

	private Integer idLineaPedido;
	private Pedido2 pedido2;
	private Produto2 produto2;
	private Double cantidade;

	public LineaPedido2() {
	}

	public LineaPedido2(Pedido2 pedido2, Produto2 produto2, Double cantidade) {
		this.pedido2 = pedido2;
		this.produto2 = produto2;
		this.cantidade = cantidade;
	}

	public Integer getIdLineaPedido() {
		return this.idLineaPedido;
	}

	public void setIdLineaPedido(Integer idLineaPedido) {
		this.idLineaPedido = idLineaPedido;
	}

	public Pedido2 getPedido2() {
		return this.pedido2;
	}

	public void setPedido2(Pedido2 pedido2) {
		this.pedido2 = pedido2;
	}

	public Produto2 getProduto2() {
		return this.produto2;
	}

	public void setProduto2(Produto2 produto2) {
		this.produto2 = produto2;
	}

	public Double getCantidade() {
		return this.cantidade;
	}

	public void setCantidade(Double cantidade) {
		this.cantidade = cantidade;
	}

	@Override
	public String toString() {
		return "\n\t-[idLineaPedido=" + idLineaPedido + ", idProduto=" + produto2.getIdProduto() + ", cantidade=" + cantidade + "]\n"+ produto2;
	}

}
