package dto;
// Generated 10 ene. 2021 17:37:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pedido2 generated by hbm2java
 */
public class Pedido2 implements java.io.Serializable {

	private Integer idPedido;
	private Cliente2 cliente2;
	private Double importe;
	private Set lineaPedido2s = new HashSet(0);

	public Pedido2() {
	}

	public Pedido2(Cliente2 cliente2, Double importe, Set lineaPedido2s) {
		this.cliente2 = cliente2;
		this.importe = importe;
		this.lineaPedido2s = lineaPedido2s;
	}

	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	public Cliente2 getCliente2() {
		return this.cliente2;
	}

	public void setCliente2(Cliente2 cliente2) {
		this.cliente2 = cliente2;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	public Set<LineaPedido2> getLineaPedido2s() {
		return this.lineaPedido2s;
	}

	public void setLineaPedido2s(Set lineaPedido2s) {
		this.lineaPedido2s = lineaPedido2s;
	}

	@Override
	public String toString() {
		return "Pedido [id=" + idPedido + ", " + cliente2 + ", importe=" + importe + ", lineaPedidos="+lineaPedido2s;
				
	}

}
